### PR TITLE
Version support

### PR DESCRIPTION
**Pull request by spangenberg**

### CODE REVIEW

**Comment by spangenberg** [comment]
/hold

Reviews are welcome, but we can't merge this or should immediately create a release afterwards. The semver package we also use in other components throws panics if the supplied version violates semver. And since we don't have a release yet this is the case.

**Comment by enxebre** [comment]
ping @spangenberg

**Comment by ingvagabund** [comment]
@mrunalp just pushed annotated tag, we can merge

/hold cancel
/approve
/lgtm

**Comment by ingvagabund** [comment]
```sh
$ ./bin/machine-controller-manager -version
ClusterAPIProviderGCP v0.0.0-beta1-4-g0ad83c2
```

**Pull request merged**
