### PR TITLE
Bug 1878880: re-vendor machine-api-operator at e0db6b65

### PR DESCRIPTION
**Pull request by elmiko**
This change is being proposed to pick up the recent log message changes as proposed in https://github.com/openshift/machine-api-operator/pull/681

### CODE REVIEW

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold

#122 includes the changes from this PR so lets merge that one and then we can close this and mark the bug appropriately

**Comment by JoelSpeed** [comment]
/close

The changes from this PR have been merged as part of #122

**Pull request closed without merging**
