### PR TITLE
Bug 1864352: Add leader election mechanism to release 4.5

### PR DESCRIPTION
**Pull request by elmiko**
This change brings in 3 cherry-pick commits which add leader election to this controller.

8b1645c7cd903be7bee705e8a629054ab40ce0db
8c872133e8bf4c68b58ef7bcc9d88b5c61f8e2ee
3739cfa20e91a837147b09f066709911c24afbea

### CODE REVIEW

**Comment by elmiko** [comment]
i'm putting a hold on this as i would like to make sure we include these commits when they land on the master branch, #115 
/hold

**Comment by elmiko** [comment]
removing the hold as #115 has merged
/hold cancel

**Comment by elmiko** [comment]
/retitle Bug 1864352: Add leader election mechanism to release 4.5

**Comment by Danil-Grigorev** [comment]
\lgtm
\approve

**Comment by Danil-Grigorev** [comment]
@JoelSpeed @enxebre Need you guys to approve this, as I was not in approvers in 4.5 release :D Sorry @elmiko

**Comment by markmc** [comment]
Landed this for aws and baremetal last week. Looks justified to avoid a nasty failure scenario.

**Pull request merged**
