### PR TITLE
Vendor: downgrade gcp sdk to v0.57.0

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit ensures we match the installer's version of
cloud.google.com/go to enable compability with terraform.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I've verified that this change doesn't break anything. The `google.golang.org/api` package was updated to include a new field from version `v0.15.0` to `v0.33.0`. This PR reverts this package to `v0.29.0` but that still contains the new field that was required.

/approve

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
