### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api-provider-gcp:release-1.2 (1d8cf4c) into master

### PR DESCRIPTION
**Pull request by damdo**
This PR merges upstream's https://github.com/kubernetes-sigs/cluster-api-provider-gcp:release-1.2 (1d8cf4c) into `master`.

Check [this comment](https://github.com/openshift/cluster-capi-operator/pull/101#issue-1564195291) for this CAPI provider bump testing status.

### CODE REVIEW

**Comment by damdo** [comment]
Infra issues:

/retest

**Comment by damdo** [comment]
For coordination with other CAPI components:

/hold

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Slight rebase due to an ART update to the build target updates, no other changes
/lgtm
/approve
/hold cancel

**Comment by damdo** [comment]
/hold

Need to wait for the main cluster-api PR to merge.

**Comment by damdo** [comment]
This is a techpreview feature and it's actually not enabled on serial tests.
That's why we think we can override this job.

/override ci/prow/e2e-gcp-serial

**Pull request merged**
