### PR TITLE
Bug 1733474: Revendor MAO with timeout formatting fix

### PR DESCRIPTION
**Pull request by alexander-demichev**
Revendor MAO with timeout formatting fix

### CODE REVIEW

**Comment by jwforres** [comment]
4.4 is in maintenance phase, please provide the justification for backport for a low severity BZ

**Comment by alexander-demichev** [comment]
/title Bug 1733474: Revendor MAO with timeout formatting fix

**Comment by alexander-demichev** [comment]
/retitle Bug 1733474: Revendor MAO with timeout formatting fix

**Pull request merged**
