### PR TITLE
OCPCLOUD-2445: Merge https://github.com/kubernetes-sigs/cluster-api-provider-gcp:v1.6.0 (be17146) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
/hold
Need to finish updating the manifests

**Comment by theobarberbany** [comment]
/retitle OCPCLOUD-2445: Merge https://github.com/kubernetes-sigs/cluster-api-provider-gcp:v1.6.0 (be17146) into master

**Comment by damdo** [comment]
Manifests updated
/unhold

**Comment by damdo** [comment]
@nrb don't worry about the test. It's failing for unrelated reasons as the provider is not even deployed there.

If you can review it, we can merge it without that test

**Comment by damdo** [comment]
e2e-gcp-serial is failing due to https://issues.redhat.com/browse/OCPBUGS-30224

Moreover this holds https://github.com/openshift/cluster-api-provider-gcp/pull/221#issuecomment-1981643830

Hence overriding
/override ci/prow/e2e-gcp-serial

**Pull request merged**
